workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-v7
      - node-v8
      - node-v9

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node
    working_directory: ~/working_directory
    steps:
      - run:
          name: Versions
          command: |
            yarn versions
            echo "npm: $(npm --version)"
      - checkout
      - restore_cache:
          keys:
            - v-yarn-lock---
            - v-yarn-lock-master--
            - v-yarn-cache--
            - v-yarn-cache-master-
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: v-yarn-lock---
          paths:
            - node_modules
      - save_cache:
          key: v-yarn-cache---
          paths:
            - /usr/local/share/.cache/yarn
            - /root/.cache/yarn
      - run:
          # Variables are not available in `path` or `paths`
          # https://discuss.circleci.com/t/can-i-use-variables-in-cache-paths/11393
          name: Check `yarn cache dir`
          command: |
            CACHE_DIR=$(yarn cache dir)
            echo "yarn cache dir: ${CACHE_DIR}"
            # v0.x or v1.x
            if [[ "$CACHE_DIR" != /usr/local/share/.cache/yarn* && "$CACHE_DIR" != /root/.cache/yarn/* ]]; then
                exit 1
            fi
  node-v7:
    <<: *node-base
    docker:
      - image: node:7
  node-v8:
    <<: *node-base
    docker:
      - image: node:8
  node-v9:
    <<: *node-base
    docker:
      - image: node:9
